apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mistral-7b
  namespace: hawk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  #storageClassName: standard
  volumeMode: Filesystem