apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen-3
  namespace: hawk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  #storageClassName: standard
  volumeMode: Filesystem